'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import PunchesPanel from './punches-panel';
import FolhaPontoPanel from './folha-ponto-panel';

type Employee = { id: string; name: string; employeeNumber: string | null; cpf?: string | null; jobTitle?: string | null; workDays?: string | null; scheduleStart?: string | null; scheduleEnd?: string | null; active: boolean; _count?: { punches: number } };
type Issue = { id: string; type: string; status: string; description: string | null; detectedAt: string; user: { name: string; employeeNumber: string | null }; punch: { id: string; type: string; timestamp: string } | null };

const emptyForm = { name: '', employeeNumber: '', cpf: '', jobTitle: '', workDays: 'SEG,TER,QUA,QUI,SEX', scheduleStart: '08:00', scheduleEnd: '18:00' };

export default function AdminDashboard({ employees: initialEmployees, stats }: { employees: Employee[]; stats: { employeeCount: number; punchesToday: number; openInconsistencies: number } }) {
  const [tab, setTab] = useState('overview');
  const [employees, setEmployees] = useState<Employee[]>(initialEmployees);
  const [form, setForm] = useState(emptyForm);
  const [editing, setEditing] = useState<Employee | null>(null);
  const [employeeSearch, setEmployeeSearch] = useState('');
  const [issues, setIssues] = useState<Issue[]>([]);
  const [message, setMessage] = useState('');
  const [saving, setSaving] = useState(false);

  const loadEmployees = useCallback(async () => { const response = await fetch('/api/admin/employees', { cache: 'no-store' }); if (response.ok) setEmployees((await response.json()).employees || []); }, []);
  const loadIssues = useCallback(async () => { const response = await fetch('/api/admin/inconsistencies', { cache: 'no-store' }); if (response.ok) setIssues((await response.json()).inconsistencies || []); }, []);
  useEffect(() => { void loadIssues(); }, [loadIssues]);

  const filteredEmployees = useMemo(() => employees.filter((item) => `${item.name} ${item.employeeNumber || ''} ${item.jobTitle || ''}`.toLowerCase().includes(employeeSearch.toLowerCase())), [employees, employeeSearch]);
  const startEdit = (employee: Employee) => { setEditing(employee); setForm({ name: employee.name, employeeNumber: employee.employeeNumber || '', cpf: employee.cpf || '', jobTitle: employee.jobTitle || '', workDays: employee.workDays || '', scheduleStart: employee.scheduleStart || '', scheduleEnd: employee.scheduleEnd || '' }); setTab('employees'); };
  const resetForm = () => { setEditing(null); setForm(emptyForm); };
  const saveEmployee = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); setMessage(''); const response = await fetch('/api/admin/employees', { method: editing ? 'PATCH' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(editing ? { ...form, id: editing.id } : form) }); const data = await response.json().catch(() => ({})); if (!response.ok) setMessage(data.error || 'Não foi possível salvar.'); else { setMessage(editing ? 'Colaborador atualizado.' : 'Colaborador cadastrado.'); resetForm(); await loadEmployees(); } setSaving(false); };
  const toggleEmployee = async (employee: Employee) => { const response = await fetch('/api/admin/employees', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id: employee.id, active: !employee.active }) }); if (response.ok) { setMessage(employee.active ? 'Colaborador desativado.' : 'Colaborador ativado.'); await loadEmployees(); } };
  const resolveIssue = async (id: string) => { const response = await fetch('/api/admin/inconsistencies', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id, status: 'RESOLVED' }) }); if (response.ok) { setMessage('Inconsistência resolvida.'); await loadIssues(); } };

  return <>
    <nav className="admin-tabs" aria-label="Seções administrativas">{[['overview', 'Visão geral'], ['employees', 'Colaboradores'], ['shifts', 'Turnos e jornada'], ['punches', 'Registros de ponto'], ['timesheet', 'Folha de ponto'], ['issues', 'Inconsistências']].map(([key, label]) => <button key={key} className={tab === key ? 'active' : ''} onClick={() => setTab(key)}>{label}</button>)}</nav>
    {message ? <div className="status-msg admin-toast">{message}</div> : null}
    {tab === 'overview' ? <section className="admin-grid"><div className="card admin-hero"><div><span className="eyebrow">OPERAÇÃO EM TEMPO REAL</span><h2>Central de gestão</h2><p className="small-muted">Acompanhe a jornada da equipe, trate pendências e mantenha os registros organizados em um só lugar.</p></div><button className="primary-btn admin-action" onClick={() => setTab('punches')}>Abrir registros</button></div><div className="stat-grid">{[['Colaboradores ativos', stats.employeeCount], ['Marcações hoje', stats.punchesToday], ['Pendências abertas', stats.openInconsistencies]].map(([label, value]) => <div className="summary" key={String(label)}><span className="small-muted">{label}</span><strong>{value}</strong></div>)}</div><div className="card admin-guide"><h3>Rotina recomendada</h3><div className="guide-row"><b>1</b><span>Confira as marcações recentes e suas evidências fotográficas.</span></div><div className="guide-row"><b>2</b><span>Revise inconsistências abertas e registre a resolução.</span></div><div className="guide-row"><b>3</b><span>Mantenha jornadas e dias de trabalho atualizados.</span></div></div></section> : null}
    {tab === 'employees' ? <section className="admin-two-col"><div className="card"><div className="section-heading"><div><h2>{editing ? 'Editar colaborador' : 'Novo colaborador'}</h2><p className="small-muted">Cadastre matrícula, função e dados de jornada.</p></div>{editing ? <button className="ghost-btn" onClick={resetForm}>Cancelar</button> : null}</div><form onSubmit={saveEmployee} className="admin-form">{[['name', 'Nome completo'], ['employeeNumber', 'Matrícula'], ['cpf', 'CPF'], ['jobTitle', 'Cargo'], ['workDays', 'Dias trabalhados'], ['scheduleStart', 'Início da jornada'], ['scheduleEnd', 'Fim da jornada']].map(([key, label]) => <label key={key} className="small-muted">{label}<input className="input" required={key === 'name' || key === 'employeeNumber'} value={form[key as keyof typeof form]} onChange={(event) => setForm({ ...form, [key]: event.target.value })} /></label>)}<button className="primary-btn" disabled={saving}>{saving ? 'Salvando...' : editing ? 'Salvar alterações' : 'Cadastrar colaborador'}</button></form></div><div className="card"><div className="section-heading"><div><h2>Equipe</h2><p className="small-muted">{employees.length} colaboradores cadastrados.</p></div></div><input className="input" placeholder="Buscar por nome, matrícula ou cargo" value={employeeSearch} onChange={(event) => setEmployeeSearch(event.target.value)} /><div className="employee-list">{filteredEmployees.map((employee) => <div className="employee-row" key={employee.id}><div><strong>{employee.name}</strong><div className="small-muted">{employee.employeeNumber || 'Sem matrícula'} · {employee.jobTitle || 'Cargo não informado'}</div></div><div className="row-actions"><span className={employee.active ? 'status-pill ok' : 'status-pill off'}>{employee.active ? 'Ativo' : 'Inativo'}</span><button className="ghost-btn" onClick={() => startEdit(employee)}>Editar</button><button className="ghost-btn" onClick={() => void toggleEmployee(employee)}>{employee.active ? 'Desativar' : 'Ativar'}</button></div></div>)}</div></div></section> : null}
    {tab === 'shifts' ? <section className="card"><div className="section-heading"><div><h2>Turnos e jornada</h2><p className="small-muted">A jornada é configurada por colaborador e alimenta a conferência operacional.</p></div><button className="ghost-btn" onClick={() => setTab('employees')}>Gerenciar colaboradores</button></div><div className="shift-table"><div className="shift-header"><span>Colaborador</span><span>Dias</span><span>Jornada</span><span>Status</span><span>Ação</span></div>{employees.map((employee) => <div className="shift-row" key={employee.id}><span><b>{employee.name}</b><small>{employee.employeeNumber || '—'}</small></span><span>{employee.workDays || 'Não definido'}</span><span>{employee.scheduleStart || '—'} às {employee.scheduleEnd || '—'}</span><span className={employee.active ? 'status-pill ok' : 'status-pill off'}>{employee.active ? 'Ativo' : 'Inativo'}</span><button className="ghost-btn" onClick={() => startEdit(employee)}>Editar</button></div>)}</div></section> : null}
    {tab === 'punches' ? <PunchesPanel employees={employees.filter((item) => item.active).map(({ id, name, employeeNumber }) => ({ id, name, employeeNumber }))} /> : null}
    {tab === 'timesheet' ? <FolhaPontoPanel employees={employees.filter((item) => item.active).map(({ id, name, employeeNumber }) => ({ id, name, employeeNumber }))} /> : null}
    {tab === 'issues' ? <section className="card"><div className="section-heading"><div><h2>Inconsistências e auditoria</h2><p className="small-muted">Pendências identificadas para revisão do gestor.</p></div><button className="ghost-btn" onClick={() => void loadIssues()}>Atualizar</button></div>{!issues.length ? <p className="small-muted">Nenhuma inconsistência aberta.</p> : <div className="employee-list">{issues.map((issue) => <div className="employee-row" key={issue.id}><div><strong>{issue.user.name} · {issue.type}</strong><div className="small-muted">{issue.description || 'Sem descrição'} · {new Date(issue.detectedAt).toLocaleString('pt-BR')}</div></div><button className="primary-btn compact-btn" onClick={() => void resolveIssue(issue.id)}>Resolver</button></div>)}</div>}</section> : null}
  </>;
}
