'use client';

import { useEffect, useMemo, useState } from 'react';

type Employee = { id: string; name: string; employeeNumber: string | null; cpf?: string | null };
type Certificate = { id: string; userId: string; startDate: string; endDate: string; daysCount: number; workDaysCount: number | null; documentName: string | null; documentMime: string | null; observation: string | null; status: string; canceledAt: string | null; cancelReason: string | null; user: { name: string; employeeNumber: string | null; cpf: string | null } };

function dateText(value: string) { return new Date(value).toLocaleDateString('pt-BR'); }
function periodDays(start: string, end: string) { if (!start || !end) return 0; const a = new Date(`${start}T12:00:00`); const b = new Date(`${end}T12:00:00`); return Math.max(0, Math.round((b.getTime() - a.getTime()) / 86_400_000) + 1); }

export default function CertificatesPanel({ employees }: { employees: Employee[] }) {
  const [items, setItems] = useState<Certificate[]>([]); const [search, setSearch] = useState(''); const [message, setMessage] = useState(''); const [saving, setSaving] = useState(false);
  const [form, setForm] = useState({ userId: '', startDate: '', endDate: '', observation: '' }); const [document, setDocument] = useState<{ name: string; mime: string; data: string } | null>(null);
  async function load() { const response = await fetch('/api/admin/certificates', { cache: 'no-store' }); const data = await response.json().catch(() => ({})); if (response.ok) setItems(data.certificates || []); else setMessage(data.error || 'Não foi possível carregar atestados.'); }
  useEffect(() => { void load(); }, []);
  const filtered = useMemo(() => items.filter(item => `${item.user.name} ${item.user.employeeNumber || ''} ${item.user.cpf || ''}`.toLowerCase().includes(search.toLowerCase())), [items, search]);
  function onFile(file: File | undefined) { if (!file) return; if (!['application/pdf', 'image/jpeg', 'image/png'].includes(file.type)) return setMessage('Aceitos somente PDF, JPG, JPEG ou PNG.'); if (file.size > 10 * 1024 * 1024) return setMessage('O documento deve ter no máximo 10 MB.'); const reader = new FileReader(); reader.onload = () => setDocument({ name: file.name, mime: file.type, data: String(reader.result) }); reader.readAsDataURL(file); }
  async function create() { if (!form.userId || !form.startDate || !form.endDate) return setMessage('Selecione o funcionário e informe o período.'); setSaving(true); setMessage(''); const response = await fetch('/api/admin/certificates', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...form, documentName: document?.name, documentMime: document?.mime, documentData: document?.data }) }); const data = await response.json().catch(() => ({})); if (!response.ok) setMessage(data.error || 'Não foi possível lançar o atestado.'); else { setMessage('Atestado lançado e auditado.'); setForm({ userId: '', startDate: '', endDate: '', observation: '' }); setDocument(null); await load(); } setSaving(false); }
  async function cancel(id: string) { const reason = window.prompt('Motivo do cancelamento:'); if (!reason) return; const response = await fetch('/api/admin/certificates', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id, action: 'cancel', reason }) }); const data = await response.json().catch(() => ({})); setMessage(response.ok ? 'Atestado cancelado e auditado.' : data.error || 'Não foi possível cancelar.'); if (response.ok) await load(); }
  return <section className="admin-two-col certificates-layout"><div className="card"><div className="section-heading"><div><span className="eyebrow">JUSTIFICATIVA FORMAL</span><h2>Lançar atestado</h2><p className="small-muted">O atestado não cria batida e prevalece sobre falta na folha.</p></div></div><label className="small-muted">Funcionário<select className="input" value={form.userId} onChange={e => setForm({ ...form, userId: e.target.value })}><option value="">Selecione por nome ou matrícula</option>{employees.map(employee => <option key={employee.id} value={employee.id}>{employee.employeeNumber || '—'} · {employee.name}</option>)}</select></label><div className="form-two-col"><label className="small-muted">Data inicial<input className="input" type="date" value={form.startDate} onChange={e => setForm({ ...form, startDate: e.target.value })} /></label><label className="small-muted">Data final<input className="input" type="date" value={form.endDate} onChange={e => setForm({ ...form, endDate: e.target.value })} /></label></div><div className="certificate-day-count">Período documental: <strong>{periodDays(form.startDate, form.endDate)} dia(s)</strong></div><label className="small-muted">Documento<input className="input" type="file" accept="application/pdf,image/jpeg,image/png" onChange={e => onFile(e.target.files?.[0])} />{document ? <small>{document.name}</small> : null}</label><label className="small-muted">Observação<textarea className="input" rows={3} value={form.observation} onChange={e => setForm({ ...form, observation: e.target.value })} /></label><button className="primary-btn" type="button" onClick={() => void create()} disabled={saving}>{saving ? 'Salvando...' : 'Lançar atestado'}</button>{message ? <p className="status-msg">{message}</p> : null}</div><div className="card"><div className="section-heading"><div><span className="eyebrow">HISTÓRICO OFICIAL</span><h2>Atestados cadastrados</h2><p className="small-muted">Sem exclusão física; cancelamentos permanecem auditados.</p></div><button className="ghost-btn" type="button" onClick={() => void load()}>Atualizar</button></div><input className="input" placeholder="Buscar nome, matrícula ou CPF" value={search} onChange={e => setSearch(e.target.value)} /><div className="certificate-list">{filtered.map(item => <div className="certificate-row" key={item.id}><div><strong>{item.user.name}</strong><span>{item.user.employeeNumber || 'Sem matrícula'} · {dateText(item.startDate)} a {dateText(item.endDate)} · {item.daysCount} dia(s)</span><small>{item.documentName || 'Sem documento'} · {item.status}</small></div>{item.status !== 'CANCELADO' ? <button className="ghost-btn" type="button" onClick={() => void cancel(item.id)}>Cancelar</button> : <span className="status-pill off">Cancelado</span>}</div>)}{!filtered.length ? <p className="small-muted">Nenhum atestado encontrado.</p> : null}</div></div></section>;
}
