'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import type { Turma } from '@/lib/beneficiarios-source';

type Participant = { id: string; nome: string; codigo?: string | number | null; turma?: string };
type Marking = 'presente' | 'falta' | 'justificado' | 'nao_compareceu';
type ExistingList = { id: string; marcacoes?: Record<string, Record<string, Marking>>; participantes?: Participant[] } | null;
const options: Array<{ key: Marking; label: string; short: string }> = [{ key: 'presente', label: 'Presente', short: 'P' }, { key: 'falta', label: 'Falta', short: 'F' }, { key: 'justificado', label: 'Justificado', short: 'J' }, { key: 'nao_compareceu', label: 'Não compareceu', short: 'N' }];
function today() { return new Date().toLocaleDateString('en-CA'); }

export default function PresencaPwaPage() {
  const [date, setDate] = useState(today()); const [turmas, setTurmas] = useState<Turma[]>([]); const [turmaId, setTurmaId] = useState(''); const [participants, setParticipants] = useState<Participant[]>([]); const [markings, setMarkings] = useState<Record<string, Marking>>({}); const [list, setList] = useState<ExistingList>(null); const [teacher, setTeacher] = useState(''); const [search, setSearch] = useState(''); const [loading, setLoading] = useState(false); const [savingId, setSavingId] = useState(''); const [message, setMessage] = useState('');
  const visible = useMemo(() => participants.filter((item) => !search || item.nome.toLocaleLowerCase('pt-BR').includes(search.toLocaleLowerCase('pt-BR')) || String(item.codigo || '').includes(search)), [participants, search]);
  const counts = useMemo(() => options.reduce((acc, option) => ({ ...acc, [option.key]: participants.filter((item) => markings[item.id] === option.key).length }), {} as Record<Marking, number>), [participants, markings]);

  const load = useCallback(async () => { setLoading(true); setMessage(''); try { const response = await fetch(`/api/modulo-3/chamada?date=${date}${turmaId ? `&turmaId=${encodeURIComponent(turmaId)}` : ''}`, { cache: 'no-store' }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Não foi possível carregar a chamada.'); setTurmas(data.turmas || []); setParticipants(data.participants || []); setList(data.existing || null); const stored: Record<string, Marking> = {}; for (const item of data.participants || []) { const saved = data.existing?.marcacoes?.[item.id]?.[String(new Date(`${date}T00:00:00Z`).getUTCDate())]; stored[item.id] = saved || 'presente'; } setMarkings(stored); } catch (error) { setMessage(error instanceof Error ? error.message : 'Não foi possível carregar a chamada.'); } finally { setLoading(false); } }, [date, turmaId]);
  useEffect(() => { const saved = window.localStorage.getItem('progredir-professor'); if (saved) setTeacher(saved); }, []);
  useEffect(() => { void load(); }, [load]);

  async function mark(item: Participant, status: Marking) { const previous = markings[item.id] || 'presente'; setMarkings((current) => ({ ...current, [item.id]: status })); setSavingId(item.id); setMessage('Sincronizando com o sistema externo…'); try { let activeList = list; if (!activeList?.id) { const create = await fetch('/api/modulo-3/chamada', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ date, turmaId, turma: turmas.find((t) => t.id === turmaId)?.nome || '', teacher, participants, markings: { [item.id]: { [String(new Date(`${date}T00:00:00Z`).getUTCDate())]: status } } }) }); const created = await create.json(); if (!create.ok) throw new Error(created.error || 'Não foi possível abrir a lista.'); activeList = created.list; setList(activeList); } else { const patch = await fetch('/api/modulo-3/chamada', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ listId: activeList.id, beneficiaryId: item.id, status, day: new Date(`${date}T00:00:00Z`).getUTCDate(), month: new Date(`${date}T00:00:00Z`).getUTCMonth() + 1, year: new Date(`${date}T00:00:00Z`).getUTCFullYear(), turmaId, teacher }) }); const updated = await patch.json(); if (!patch.ok) throw new Error(updated.error || 'Não foi possível sincronizar.'); setList(updated.list); } setMessage(`Presença de ${item.nome} sincronizada agora.`); } catch (error) { setMarkings((current) => ({ ...current, [item.id]: previous })); setMessage(error instanceof Error ? error.message : 'Falha ao sincronizar.'); } finally { setSavingId(''); } }
  function setProfessor(value: string) { setTeacher(value); window.localStorage.setItem('progredir-professor', value); }

  return <main className="module3-shell presence-pwa-shell"><header className="module3-header"><div><span className="eyebrow">MÓDULO 3 · PWA DO PROFESSOR</span><h1>Lista de presença</h1><p>Marque e sincronize cada criança em tempo real.</p></div><div className="module3-actions"><a className="ghost-btn" href="/modulo-3">Beneficiários</a><a className="ghost-btn" href="/admin">Administração</a></div></header><section className="card presence-controls"><label><span>Professor(a)</span><input className="input" value={teacher} onChange={(event) => setProfessor(event.target.value)} placeholder="Digite seu nome" /></label><label><span>Data da aula</span><input className="input" type="date" value={date} onChange={(event) => setDate(event.target.value)} /></label><label><span>Turma</span><select className="input" value={turmaId} onChange={(event) => setTurmaId(event.target.value)}><option value="">Todos os beneficiários ativos</option>{turmas.map((item) => <option value={item.id} key={item.id}>{item.nome}</option>)}</select></label><button className="primary-btn" type="button" onClick={() => void load()} disabled={loading}>{loading ? 'Carregando…' : 'Atualizar chamada'}</button></section><section className="card presence-call-card"><div className="section-heading"><div><span className="eyebrow">CHAMADA AO VIVO</span><h2>{participants.length} crianças e adolescentes</h2><p className="small-muted">Cada toque envia a alteração diretamente ao sistema de beneficiários.</p></div><input className="input presence-search" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Buscar nome ou código" /></div><div className="presence-live-status"><strong>{message || 'Pronto para marcar.'}</strong><span>Presentes {counts.presente || 0} · Faltas {counts.falta || 0} · Justificados {counts.justificado || 0}</span></div>{participants.length === 0 && !loading ? <div className="module3-empty">Nenhum beneficiário ativo encontrado para esta turma.</div> : <div className="presence-roster">{visible.map((item) => <article className="presence-roster-row" key={item.id}><div className="presence-roster-name"><strong>{item.nome}</strong><small>Código {item.codigo || '—'}</small></div><div className="presence-options">{options.map((option) => <button type="button" key={option.key} className={`presence-option ${markings[item.id] === option.key ? `selected ${option.key}` : ''}`} disabled={savingId === item.id} onClick={() => void mark(item, option.key)}><b>{option.short}</b><span>{option.label}</span></button>)}</div>{savingId === item.id ? <span className="presence-syncing">Sincronizando…</span> : null}</article>)}</div>}</section></main>;
}
